[workspace]
resolver = "2"
members = ["nekoton"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[patch."https://github.com/tonlabs/ton-labs-types.git"]
ton_types = { version = "1.3.33", git = "https://github.com/broxus/ton-labs-types.git" }
