[workspace]
members = ["nekoton"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[patch."https://github.com/tonlabs/ton-labs-types.git"]
ton_types = { git = "https://github.com/broxus/ton-labs-types.git" }
